Thermostat_changes_file: "thermostat_changes.txt"

Advise:
  Print_Graph: False
  Lambda: 0.995
  Hours: 4
  Maximum_Safety_Temp: 86
  Minimum_Safety_Temp: 54
  Heating_Consumption: 0.075  # kwatts
  Cooling_Consumption: 1.25  # kwatts
  Max_Actions: 400 #int
  Thermal_Precision: 400. #float
  Occupancy_Obs_Len_Addition: 4
  Setpoint: [[["00:00", "07:00", 62., 85.], ["07:00", "18:00", 70., 76.], ["18:00", "00:00", 62., 85.]], [["00:00", "00:00", 62, 85]]]

SimpleDR: False

Interval_Length: 15  # in minutes

Thermostat_Write_Tries: 10

Data_Manager:
  Pytz_Timezone: "America/Los_Angeles"
  Server : False
  Zone: "SouthZone"
  Hod_Client: "ciee/hod"
  Entity_File: "fill_this.ent"
  Agent_IP: '1.3.3.7:1337'
  Wunderground_Key: '147c8cec00fcd16d'
  Wunderground_Place: 'KCABERKE67'
  UUIDS:
      Thermostat_high: 'dbbf4a91-107a-3b15-b2c0-a49b54116daa'
      Thermostat_low: 'eeadc8ed-6255-320d-b845-84f44748fe95'
      Thermostat_mode: 'a4639323-1e57-3512-83fb-b01234378fd8'
      Thermostat_temperature: '03099008-5224-3b61-b07e-eee445e64620'
      Thermostat_state: 'dfb2b403-fd08-3e9b-bf3f-18c699ce40d6'
      Energy_cost: '9dc5b5cd-8cb1-3dd3-b582-5ed6bf3f0083'
      Temperature_Outside: '1c467b79-b314-3c1e-83e6-ea5e7048c37b'

Pricing:
  #First sublist is weekday, second list is weekend
  Energy_Rates: "PDP-Winter" # options are "Server", "NON-TOU-Summer", "NON-TOU-Winter", "TOU-Summer", "TOU-Winter", "PDP-Summer", "PDP-Winter"
  Holiday: "False"
  NON-TOU-Summer: [[["00:00", "00:00", 0.25]], [["00:00", "00:00", 0.25]]]
  NON-TOU-Winter: [[["00:00", "00:00", 0.19]], [["00:00", "00:00", 0.19]]]
  TOU-Summer: [[["00:00", "08:30", 0.21],["08:30", "12:00", 0.24],["12:00", "18:00", 0.26],["18:00", "21:30", 0.24],["21:30", "00:00", 0.21]], [["00:00","00:00",0.21]]]
  TOU-Winter: [[["00:00", "08:30", 0.20],["08:30", "21:30", 0.22],["21:30", "00:00", 0.20]], [["00:00","00:00",0.20]]]
  PDP-Summer: [[["00:00", "08:30", 0.21],["08:30", "12:00", 0.24],["12:00", "14:00", 0.26],["14:00", "18:00", 0.60],["18:00", "21:30", 0.24], ["21:30", "00:00", 0.21]], [["00:00","14:00",0.21],["14:00","18:00",0.60],["18:00","00:00",0.21]]]
  PDP-Winter: [[["00:00", "08:30", 0.20],["08:30","14:00", 0.22],["14:00", "18:00", 0.60],["18:00", "21:30", 0.22],["21:30", "00:00", 0.20]], [["00:00","14:00",0.20],["14:00","18:00",0.60],["18:00","00:00",0.20]]]