
UUIDS:
    thermostat_high: '0d037818-02c2-3e5b-87e9-94570d43b418'
    thermostat_low: '6cbee2ae-06e7-3fc3-a2fc-698fa3deadee'
    thermostat_mode: '22e4f56b-1147-3302-83df-c7631b9b0b79'
    thermostat_temperature: 'c05385e5-a947-37a3-902e-f6ea45a43fe8'
    thermostat_state: '187ed9b8-ee9b-3042-875e-088a08da37ae'
    energy_cost: '9dc5b5cd-8cb1-3dd3-b582-5ed6bf3f0083'

zone: "CentralZone"

energy_rates: "winter_rates" # options are "server", "summer_rates", "winter_rates", "event_day_rates"

thermostat_changes_file: "thermostat_changes.txt"

advise:
    lambda: 0.995
    interval_Length: 15  # in minutes
    hours: 4
    maximum_Safety_Temp: 86
    minimum_Safety_Temp: 54
    heating_Consumption: 4000  # watts
    cooling_Consumption: 4000  # watts

SimpleDR: True

Server: True
